### ISSUE TITLE
Error Code from Equipment Controllers

### ISSUE THREAD

**Issue by liddafire** [sierrataylor/safety-equipment-inspection-app#141]
When opening the forms page from the dashboard, 
EquipmentControllers.cs
Line 18

System.InvalidOperationException
  HResult=0x80131509
  Message=Error reading credential file from location .\firestoreCredentials.json: Could not find file 'C:\Users\user\Documents\GitHub\safety-equipment-inspection-app\SafetyEquipmentInspection\SafetyEquipmentInspectionAPI\firestoreCredentials.json'.
Please check the value of the Environment Variable GOOGLE_APPLICATION_CREDENTIALS
  Source=Google.Apis.Auth
  StackTrace:
   at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.<CreateDefaultCredentialAsync>d__11.MoveNext()
   at Google.Api.Gax.Grpc.DefaultChannelCredentialsCache.<<-ctor>b__5_1>d.MoveNext()
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.Firestore.V1.FirestoreClientBuilder.BuildImpl()
   at Google.Cloud.Firestore.FirestoreDbBuilder.Build()
   at SafetyEquipmentInspectionAPI.Controllers.EquipmentController..ctor() in C:\Users\user\Documents\GitHub\safety-equipment-inspection-app\SafetyEquipmentInspection\SafetyEquipmentInspectionAPI\Controllers\EquipmentController.cs:line 18
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass7_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FileNotFoundException: Could not find file 'C:\Users\user\Documents\GitHub\safety-equipment-inspection-app\SafetyEquipmentInspection\SafetyEquipmentInspectionAPI\firestoreCredentials.json'.

It does not break the program (from what I can tell) but it does redivert you back to the code

**Comment by liddafire** [comment]
it also comes up when going to the forms page through the scanner

**Comment by sierrataylor** [comment]
Are you still having this problem?
